# Dependencies
markdown:      redcarpet
#markdown:     kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments
highlighter: true
#highlighter:  rouge



# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dawine Pierre
tagline:          'Rural & Software Engineer, Data Scientist, GIS Specialist'
description:      'Rural & Software Engineer, Data Scientist, GIS Specialist'
url:               http://dawine.info
# baseurl:          /pdawine.github.io/
baseurl:          /

author:
  name:           'Dawine Pierre'
  url:            https://twitter.com/pdawine

#paginate:         5
paginate:         1

# Custom vars
version:          2.1.0


github:
me: https://github.com/pdawine
